server:
  port: ${notify.port}

spring:
  application:
    name: service-notify
  datasource:
      name: test
      url: jdbc:mysql://localhost:3306/notify?useSSL=true&useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#  zipkin:
#    base-url: ${notify.zipkin.url}

mybatis:
  mapperLocations: classpath:mybatis/*.xml
  typeAliasesPackage: com.faker.notify.entity
